[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
poolver_yield_vault = "A3ERUDLAdqdwgqgAoYLftxA6F1QtxSHZYu8DpNDXyyUp"
poolver_yield_defi = "DAitPF7KHzRDVWcV4XM3J7dYGrKJkH332dQHPYUiP7UP"
poolver_reserve = "CfxRT3jsXWQZRev67ztqaNKCrHaKF6ieW9a1E8NDPvnx"
poolver_core = "2SsxJqMCYKCYesfzfXASgAPPz153j8tYMXpMKKmt2QXk"

[programs.devnet]
poolver_yield_vault = "A3ERUDLAdqdwgqgAoYLftxA6F1QtxSHZYu8DpNDXyyUp"
poolver_yield_defi = "DAitPF7KHzRDVWcV4XM3J7dYGrKJkH332dQHPYUiP7UP"
poolver_reserve = "CfxRT3jsXWQZRev67ztqaNKCrHaKF6ieW9a1E8NDPvnx"
poolver_core = "2SsxJqMCYKCYesfzfXASgAPPz153j8tYMXpMKKmt2QXk"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "cargo test"

[hooks]
