export {
  POOLVER_CORE_PROGRAM_ID,
  POOLVER_RESERVE_PROGRAM_ID,
  POOLVER_YIELD_VAULT_PROGRAM_ID,
  POOLVER_YIELD_DEFI_PROGRAM_ID,
  USDC_MINT_DEVNET_DEFAULT,
  USDC_MINT_MAINNET,
  USDC_DECIMALS,
  POOL_SIZE,
  TOTAL_MONTHS,
  MIN_CONTRIBUTION,
  MAX_CONTRIBUTION,
  DEFAULT_BID_WINDOW_SECS,
  DEFAULT_REVEAL_WINDOW_SECS,
  DEFAULT_MONTH_DURATION_SECS,
  DEFAULT_PROTOCOL_FEE_BPS,
  DEFAULT_VAULT_RESERVE_FEE_BPS,
  DEFAULT_DEFI_RESERVE_FEE_BPS,
  BID_STAKE_BPS,
  BID_CAP_BPS,
  LATE_PENALTY_BPS,
  BPS_DENOMINATOR,
  GRACE_PERIOD_SECS,
  SUSPENSION_THRESHOLD_SECS,
  LIQUIDATION_THRESHOLD_SECS,
} from "@poolver/client";

export const DEVNET_RPC =
  process.env.NEXT_PUBLIC_SOLANA_RPC || "https://api.devnet.solana.com";
